### PR TITLE
Create admin post routes

### PR DESCRIPTION
**Pull request by Kookiie88**
Sure, here's a revised version of the pull request description:

---

In this update, we've implemented POST routes for both movies and screenings. Now, you can easily add new movies and schedule screenings through our API.

To add a movie, simply make a POST request to `localhost:3000/api/movies` using Postman with the following JSON format:

```json
{
    "id": "1",
    "title": "Movie Title",
    "description": "Movie Description",
    "imdbRating": "8.5",
    "url": "http://example.com/image.jpg",
    "alt": "Movie Image",
    "releaseDate": "2022-01-01",
    "genre": ["Action", "Adventure"]
}
```

To add a screening, simply make a POST request to `localhost:3000/api/screenings` using Postman with the following JSON format:

```json
{
    "movieID": "1",
    "date": "2022-12-31",
    "startTime": "20:00"
}
```

This update streamlines the process of adding new content to our platform, enhancing its usability and flexibility.

### CODE REVIEW

**Comment by Kookiie88** [comment]
This pull request is linked to PBI #7, #8

**Review by AnnaLenaO — COMMENTED** [review]
Very nice with a description in the PR of how to add a movie and screening to the database. 
The screeningModel.js is changed from having date and startTime as type: Date to type:String. What is the reason for that?
The routes for getting a movie's dates and times are written for the type: Date. Please look 
 in the branch screeningTimes and comment on what you think of it regarding the type Date or type String. The routes can, of course, be changed to fit the type String if necessary. That should be of no problem.

**Comment by Kookiie88** [comment]
We have undone the changes we did to the screeningModal and changed our code to be working with date

**Review by AnnaLenaO — APPROVED** [review]
ok, then Date will be used also in the code for fetch screening dates & times.

**Pull request merged**
