### PR TITLE
Booking modal

### PR DESCRIPTION
**Pull request by MatsJoh50**
Placeholder UI for booking page.

90% done UI for the booking modal with 100% working pathway.

I see no real downside of making the missing UI togethter withe functions since it's forms that are bound to payment.

while this is a big PR, it's mainly UI with some small callbacks/props for navigation and UI purpose.

#32 #36 #29 #33 #31 #30 #34 (#29 )

edit: some cleanup and removal of 'dead' code beloning to other pbi's and branches

### CODE REVIEW

**Review by Kookiie88 — COMMENTED** [review]
I am getting a problem when trying to run npm run dev while in this branch, It says that clsx is not installed. Even though i have run npm install, but it seems to be missing from the package.json file.

image

I would also suggest that you change to fetch the saloon layouts from the database instead of from a json file

**Review by Weeezzt — APPROVED** [review]
I like the look of the page with the placeholder content and it seems like youve followed our prototype extensively, i understand that this is just getting it to look right before you fetch the information from the database. As you said yourself, theres some fine tuning with the styling that needs to get done but overall i like the modals and the page. Good work.

**Comment by Weeezzt** [comment]
The problem Alexander mentioned was not a problem for me, i got the error but then i ran npm install and it all worked!

**Comment by Kookiie88** [comment]
The problem that i have solved looks fixed now and the, the design looks good for me.

**Review by Kookiie88 — APPROVED** [review]

**Pull request merged**
